default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  timeout: 5000

development:
  <<: *default
  database: rumble_development

test:
  <<: *default
  database: rumble_test

production:
  <<: *default
  database: rumble_production
  password: 8dRWtU7zUsCNzW
